project:
  type: default
  execute-dir: file
  #output-dir: _output
  #render: 
  #  - index.qmd
  #  - examples/_example-R_final.qmd
  #  - examples/_example-py_final.qmd

title: Level Up Your Reproducibility Game with Quarto
author: Bjorn and Claudiu
execute: 
  freeze: true
example-title: 'Catchy title or pun: the actual title'
example-author: Me and Al
example-keywords: this; is; science!
example-filename: my-article.qmd
